package com.veyndan.paper.reddit.api;

import com.ryanharter.auto.value.moshi.MoshiAdapterFactory;
import com.squareup.moshi.JsonAdapter;

/**
 * A {@link JsonAdapter.Factory} that adds <i>all</i> {@code JsonAdapter}'s generated by
 * auto-value-moshi.
 */
@MoshiAdapterFactory
public abstract class JsonAdapterFactory implements JsonAdapter.Factory {

    public static JsonAdapter.Factory create() {
        return new AutoValueMoshi_JsonAdapterFactory();
    }
}
