package com.veyndan.redditclient.api.reddit.model;

public class Features {
    public boolean inlineImagePreviewsLoggedOut;
    public Experiment relevancyMweb;
    public Experiment relevancySidebar;
    public boolean liveHappeningNow;
    public boolean adserverReporting;
    public boolean inlineImagePreviewsLoggedIn;
    public boolean legacySearchPref;
    public boolean mobileWebTargeting;
    public boolean adzerkDoNotTrack;
    public boolean stickyComments;
    public boolean upgradeCookies;
    public boolean adsAutoRefund;
    public boolean adsAuction;
    public boolean imgurGifConversion;
    public boolean imageScraper;
    public boolean expandoEvents;
    public boolean euCookiePolicy;
    public boolean forceHttps;
    public boolean mobileNativeBanner;
    public boolean doNotTrack;
    public boolean stylesheetsEverywhere;
    public boolean newLoggedinCachePolicy;
    public Experiment registrationCaptcha;
    public boolean httpsRedirect;
    public boolean screenviewEvents;
    public boolean pauseAds;
    public boolean giveHstsGrants;
    public boolean newReportDialog;
    public boolean moatTracking;
    public boolean subredditRules;
    public boolean timeouts;
    public boolean mobileSettings;
    public boolean youtubeScraper;
    public boolean activityServiceWrite;
    public boolean adsAutoExtend;
    public boolean postEmbed;
    public boolean autoexpandMediaSubredditSetting;
    public boolean adblockTest;
    public boolean activityServiceRead;
}
