package com.veyndan.redditclient.api.reddit.model;

import java.util.ArrayList;
import java.util.List;

public class Prefs {
    public String defaultThemeSr;
    public Boolean threadedMessages;
    public Boolean hideDowns;
    public Boolean showStylesheets;
    public Boolean showLinkFlair;
    public Boolean credditAutorenew;
    public Boolean showTrending;
    public Boolean privateFeeds;
    public Boolean monitorMentions;
    public Boolean showSnoovatar;
    public Boolean research;
    public Boolean ignoreSuggestedSort;
    public Integer numComments;
    public Boolean clickgadget;
    public Boolean useGlobalDefaults;
    public Boolean labelNsfw;
    public Boolean affiliateLinks;
    public Boolean over18;
    public Boolean emailMessages;
    public Boolean highlightControversial;
    public Boolean noProfanity;
    public Boolean domainDetails;
    public Boolean collapseLeftBar;
    public String lang;
    public Boolean hideUps;
    public Boolean publicServerSeconds;
    public Boolean hideFromRobots;
    public Boolean compress;
    public Boolean storeVisits;
    public Boolean threadedModmail;
    public Integer minLinkScore;
    public String mediaPreview;
    public Boolean enableDefaultThemes;
    public List<String> contentLangs = new ArrayList<>();
    public Object showPromote;
    public Integer minCommentScore;
    public Boolean publicVotes;
    public Boolean organic;
    public Boolean collapseReadMessages;
    public Boolean showFlair;
    public Boolean markMessagesRead;
    public Boolean forceHttps;
    public Boolean hideAds;
    public Boolean beta;
    public Boolean newwindow;
    public Integer numsites;
    public Boolean legacySearch;
    public String media;
    public Boolean showGoldExpiration;
    public Boolean highlightNewComments;
    public String defaultCommentSort;
    public Boolean hideLocationbar;
}
