package com.veyndan.paper.reddit.api.reddit.model;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.util.ArrayList;
import java.util.List;

public class Prefs {
    @Nullable public String defaultThemeSr;
    @Nullable public Boolean threadedMessages;
    @Nullable public Boolean hideDowns;
    @Nullable public Boolean showStylesheets;
    @Nullable public Boolean showLinkFlair;
    @Nullable public Boolean credditAutorenew;
    @Nullable public Boolean showTrending;
    @Nullable public Boolean privateFeeds;
    @Nullable public Boolean monitorMentions;
    @Nullable public Boolean showSnoovatar;
    @Nullable public Boolean research;
    @Nullable public Boolean ignoreSuggestedSort;
    @Nullable public Integer numComments;
    @Nullable public Boolean clickgadget;
    @Nullable public Boolean useGlobalDefaults;
    @Nullable public Boolean labelNsfw;
    @Nullable public Boolean affiliateLinks;
    @Nullable public Boolean over18;
    @Nullable public Boolean emailMessages;
    @Nullable public Boolean highlightControversial;
    @Nullable public Boolean noProfanity;
    @Nullable public Boolean domainDetails;
    @Nullable public Boolean collapseLeftBar;
    @Nullable public String lang;
    @Nullable public Boolean hideUps;
    @Nullable public Boolean publicServerSeconds;
    @Nullable public Boolean hideFromRobots;
    @Nullable public Boolean compress;
    @Nullable public Boolean storeVisits;
    @Nullable public Boolean threadedModmail;
    @Nullable public Integer minLinkScore;
    @Nullable public String mediaPreview;
    @Nullable public Boolean enableDefaultThemes;
    @NonNull public List<String> contentLangs = new ArrayList<>();
    @Nullable public Object showPromote;
    @Nullable public Integer minCommentScore;
    @Nullable public Boolean publicVotes;
    @Nullable public Boolean organic;
    @Nullable public Boolean collapseReadMessages;
    @Nullable public Boolean showFlair;
    @Nullable public Boolean markMessagesRead;
    @Nullable public Boolean forceHttps;
    @Nullable public Boolean hideAds;
    @Nullable public Boolean beta;
    @Nullable public Boolean newwindow;
    @Nullable public Integer numsites;
    @Nullable public Boolean legacySearch;
    @Nullable public String media;
    @Nullable public Boolean showGoldExpiration;
    @Nullable public Boolean highlightNewComments;
    @Nullable public String defaultCommentSort;
    @Nullable public Boolean hideLocationbar;
}
